// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EOgrenciTakipAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612095033_Demo35")]
    partial class Demo35
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EOgrenciTakipAPI.Model.Alan", b =>
                {
                    b.Property<string>("AlanID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlanID");

                    b.ToTable("Alanlar");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.DersBilgisi", b =>
                {
                    b.Property<string>("DersProgramiID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KonuBilgisiID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Ay")
                        .HasColumnType("int");

                    b.Property<string>("Hafta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HaftadaDerseAyrilanSure")
                        .HasColumnType("int");

                    b.HasKey("DersProgramiID", "KonuBilgisiID");

                    b.HasIndex("KonuBilgisiID");

                    b.ToTable("DersBilgileri");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.DersProgrami", b =>
                {
                    b.Property<string>("DersProgramiID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GunlukCalismaSaati")
                        .HasColumnType("int");

                    b.Property<int>("HaftadaCalisilacakGunSayisi")
                        .HasColumnType("int");

                    b.HasKey("DersProgramiID");

                    b.ToTable("DersProgramlari");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.KonuBilgisi", b =>
                {
                    b.Property<string>("KonuBilgisiID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KonuIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KonuBilgisiID");

                    b.ToTable("KonuBilgileri");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.MufredatDersler", b =>
                {
                    b.Property<string>("MufredatDersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DersIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersSinavTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MufredatDersId");

                    b.ToTable("MufredatDersler");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.MufredatKonular", b =>
                {
                    b.Property<string>("MufredatKonuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DersIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersSinavTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MufredatKonuId");

                    b.ToTable("MufredatKonular");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxHedef")
                        .HasColumnType("int");

                    b.Property<int>("MinHedef")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.DersBilgisi", b =>
                {
                    b.HasOne("EOgrenciTakipAPI.Model.DersProgrami", "DersProgrami")
                        .WithMany("DersBilgileri")
                        .HasForeignKey("DersProgramiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EOgrenciTakipAPI.Model.KonuBilgisi", "KonuBilgisi")
                        .WithMany("DersBilgileri")
                        .HasForeignKey("KonuBilgisiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersProgrami");

                    b.Navigation("KonuBilgisi");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.DersProgrami", b =>
                {
                    b.Navigation("DersBilgileri");
                });

            modelBuilder.Entity("EOgrenciTakipAPI.Model.KonuBilgisi", b =>
                {
                    b.Navigation("DersBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
